openapi: 3.1.1
info:
  title: Bitlyzer
  summary: A REST API that exposes endpoints to create a short URL mapped to a longer URL
  version: 1.0.0
  contact:
    name: Mahesh Kumaar Balaji
    email: maheshkumaar.balaji@mkbdgs.com
  license:
    name: MIT
paths:
  /user/register:
    post:
      summary: Register a new user and generate API key needed to access the functionalities exposed
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  description: Display name of the user
                  type: string
                email:
                  description: Email address of the user
                  type: string
              required:
                - name
                - email
      responses:
        200:
          description: Response returned when user has been successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  Email:
                    description: User email address registered
                    type: string
                  Name:
                    description: User display name registered
                    type: string
                  ApiKey:
                    description: API key generated for the user
                    type: string
        415:
          $ref: '#/components/responses/InvalidContentType'
        500:
          $ref: '#/components/responses/ServerError'
        400:
          description: Response returned when user email provided is already registered.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BadRequest'
  /link/create:
    post:
      summary: Create short URL and map it to the given long URL and facilitate the redirect.
      operationId: createLink
      security:
        api_key: []
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                link:
                  description: The long URL for which a short URL needs to be created and mapped.
                  type: string
              required:
                - link
      responses:
        415:
          $ref: '#/components/responses/InvalidContentType'
        500:
          $ref: '#/components/responses/ServerError'
        400:
          description: Response returned when link provided is already available in the system.
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/BadRequest'
        200:
          description: Response returned when the short URL is created and mapped.
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    description: Key generated for the short URL.
                    type: string
                  short_url:
                    description: Complete short URL which will redirect you to the mapped link.
                    type: string
                  long_url:
                    description: The link (long url) that the short url redirects to.
                    type: string
  /link:
    parameters:
      - name: hash
        in: path
        description: key generated for the long URL provided.
        required: true
        schema:
          type: string
    get:
      summary: redirect the short url to its mapped long url
      operationId: redirectToLink
      security:
        api_key: []
      responses:
        302:
          description: Redirects the short url to the mapped long url.
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
    delete:
      summary: deletes the short url from the system.
      operationId: deleteLink
      security:
        api_key: []
      responses:
        200: 
          description: Successfully deleted the short url from the system.
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
components:
  responses:
    NotFound:
      description: The resource requested was not found
    ServerError:
      description: The operation requested could not be performed due to an internal server error.
    InvalidContentType:
      description: The request data sent is not JSON.
  securitySchemes:
    api_key:
      type: apiKey
      name: x-apikey
      in: header
  schemas:
    BadRequest:
      type: object
      properties:
        code:
          description: Error code denoting the nature of error.
          type: string
        message:
          description: Complete error message explaining the error in much more detail.
          type: string